services:
  urzedasai:
    build: .
    container_name: urzedasai
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /volume1/documents:/docs:ro   #nas docs location
    environment:
      - DOCS_ROOT=/docs
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
